elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9300:9200"
# logstash:
#   image: logstash:latest
#   command: logstash -f /etc/logstash/conf.d/logstash.conf
#   volumes:
#     - ./logstash/config:/etc/logstash/conf.d
#     - /var/log/nginx:/logs
#   ports:
#     - "5000:5000"
#   links:
#     - elasticsearch
# kibana:
#   build: kibana/
#   volumes:
#     - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
#   ports:
#     - "5601:5601"
#   links:
#     - elasticsearch
